Error Recovery
glimmerjs/glimmer-vm pull request #1462
Opened 2023-10-24 23:35 UTC by wycats

This pull request implements error recovery in the VM.

More information to come.

2023-10-26 15:48 UTC, NullVoxPopuli commented on packages/@glimmer/debug/lib/generated/op-list.ts
> +  null,
what is the purpose of these nulls?

2023-10-26 15:52 UTC, NullVoxPopuli commented on packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
> +    // ReplayableIf(
don't forget that this is commented out!

2023-10-29 02:31 UTC, NullVoxPopuli commented
I extracted the lint dependency updates to here: https://github.com/glimmerjs/glimmer-vm/pull/1474

2023-10-29 16:53 UTC, NullVoxPopuli commented
rebase should make the diff significantly smaller

2023-11-13 19:15 UTC, NullVoxPopuli commented
I'm going to be helping rebase, but:
A note on conflicting changes:
- dom-change-list is no longer in this repo, it's moved to another repo
- all the package.json scripts needed to change, due improper-for-ember configuration
- lint configs had to change due in order to work with CI and turbo
- various bugfixes in interfaces, reference, and runtime that were needed for ember-source

2023-11-20 04:21 UTC, chancancode commented on .eslintrc.cjs
What's up with this diff?

2023-11-20 04:25 UTC, chancancode commented on .eslintrc.cjs
– and, in general, now that this is in (from what I understand) a ready for merge/review state, can you back out all these unrelated config/workflow changes into a separate PR and land them first or separately later? Don't want to merge a big experimental new feature (which has a non-zero chance of needed to be reverted later) with a lot of unrelated changes.

2023-11-20 04:33 UTC, chancancode requested changes
I don't think I'll be able to successfully review this in the current state in the amount of time I had allocated for the task. (To be fair, it was still marked as draft, but I was recently told it's ready.)

Let me know when it is cleaned up with the unrelated changes backed out; especially for the formatting changes, I would strongly prefer to have them landed ahead of time and this rebased on top (which, I think @NullVoxPopuli had already started doing).

2024-01-24 17:30 UTC, NullVoxPopuli commented
Closing due to conflicts and https://github.com/glimmerjs/glimmer-vm/pull/1501 supersedes

2024-01-24 17:30 UTC, closed without merging