Streamline append VM implementation and remove enums
glimmerjs/glimmer-vm pull request #1643
Opened 2024-10-30 16:38 UTC by wycats

This PR begins the process of incrementally implementing many of the improvements in the error recovery branch.

I'm going to start with the easy stuff and work my way up to more complicated parts of the implementation, and in that spirit, this PR has two changes:

1. Streamline the AppendVM by using private fields and an optional `debug` field pattern. This simplifies the implementation and also makes it possible to consolidate `InternalAppendVM` into the normal `VM`. The benefit of the "opcode-only" subset of the VM was waning anyway, and most of the remaining distinction had to do with private implementation details that are no longer present in the `VM` interface because they're now implemented using private fields.
2. Replace `const enum` and `enum` with normal constants and literal types. There was a good reason for us to use `const enum` when we originally made the decision. But the dynamics have changed. Between (a) the fact that we can't reliably that `const enum` will be compiled away anymore, and (b) the fact that TS now has literal types, using normal constants and literal types is a better choice.

2024-10-30 17:44 UTC, NullVoxPopuli commented on packages/@glimmer/compiler/index.ts
> +export * from './lib/builder/constants';
there is a lot in here: https://github.com/glimmerjs/glimmer-vm/pull/1643/files#diff-f881a95cdbb07c9ee63e2f6fca320f7d00323b27434dbee753f4cffb38d30a85R6

does it all need to be public API?

2024-10-30 17:45 UTC, NullVoxPopuli commented on packages/@glimmer/compiler/lib/builder/constants.ts
is this file generated?

2024-10-30 17:49 UTC, NullVoxPopuli approved these changes
I'm surprised how much getting rid of enums helps with general readability

2024-10-30 17:58 UTC, NullVoxPopuli commented
Ope -- this is a regression 
![image](https://github.com/user-attachments/assets/67feaebe-5126-464e-84f2-e70442674be5)

2024-10-30 17:59 UTC, NullVoxPopuli requested changes
We have a significant perf regression for some reason.

2024-10-31 01:59 UTC, wycats commented on packages/@glimmer/compiler/index.ts
> +export * from './lib/builder/constants';
It was all public API but sucked into the `Builder` enum. And the codebase already does a lot of `export *`.

2024-10-31 01:59 UTC, wycats commented on packages/@glimmer/compiler/lib/builder/constants.ts
Negative.

2024-10-31 02:05 UTC, NullVoxPopuli commented on packages/@glimmer/compiler/lib/builder/constants.ts
it's not too bad

2024-11-03 23:50 UTC, wycats commented
Superseded by:

- #1645 
- #1646 
- #1647 
- #1648

2024-11-03 23:50 UTC, closed without merging